

export default {
    route: "home",
    heading: {
        title: "About",
        subtitle: "Biography"
    },
    content: [
        "Quinn Dizon is a composer, conductor, and programmer from Santa Rosa, California. His work as a composer has earned him recognition in the United States and Europe. Quinn’s achievements cover a wide range of awards and performances, and he has completed several commissions for a myriad of special occasions and events. Among his achievements are Grand Prize in the PARMA International Student Composer Competition for his work, Awakening, and first place in the University of Maryland College Park Walsum Competition for Dark Nebula. ",
        "Quinn holds a Bachelors of Music in Composition from the College of Wooster, and both a Masters in Composition and a Masters in Orchestral Conducting from the University of Louisville. He currently resides in the Washington D.C. area and is a doctoral candidate in composition at the University of Maryland College Park. Since 2015, he has been the recipient of the distinguished Flagship Fellowship award, given to only ten incoming doctoral students across all disciplines at UMD.",
        "In recent years, Quinn has worked as a conductor and Artistic Director in a number of ensembles and professional music organizations. In this capacity, he has consistently been a strong supporter for the performance of new music. Between 2013-2015, he served as a conductor with the then Louisville based contemporary opera company, Thompson Street Opera Company. When he arrived at the University of Maryland College Park, he immediately stepped into a leadership role in the student led TEMPO New Music Ensemble. From 2015-2017, Quinn performed in TEMPO as a clarinetist and conductor, and served on the board of directors. For the 2017-2018 season, he became the Artistic Director. Under his guidance, TEMPO was able to produce six performance events during the season, including two interactive sound installations that Quinn personally designed. With TEMPO already established as a new music ensemble in the area, Quinn worked with other students and musicians to create a new music concert series at a local performance venue, MilkBoy ArtHouse. This new series provided UMD student composers with the opportunity to have their music performed for new audiences outside the university. The inaugural concert was a success, and this concert series remains a part of TEMPO’s regular season schedule.",
        "In addition to his work as a professional musician, Quinn is a passionate music educator. He has taught composition and conducting courses for young musicians, aged 8-12, as well as college level courses in music theory, aural skills, composition, conducting, and music technology. In 2018, Quinn was awarded an Outstanding Graduate Assistant Award from the University of Maryland at College Park. This award recognized him as a top graduate teaching assistant in the school of music, and among the top two percent of teaching assistants across all disciplines on campus.",
        "Quinn is also a self taught programmer and web developer. Much of his work in this field combines his passion for music and education with his fascination with technology. Among his creations are several sound installations, music composition tools, and web applications for use in the classroom.",
    ]
}